### ISSUE TITLE
Error 13

### ISSUE THREAD

**Issue by RandomGuy908** [Malin001/Legilimens-Hogwarts-Legacy-Collectible-Finder#14]
Whenever I point Legilimens.exe to my save game folder

C:\Users\-user-\AppData\Local\Hogwarts Legacy\Saved\SaveGames

It comes back with this error

```
.sav file path: C:\Users\-user-\AppData\Local\Hogwarts Legacy\Saved\SaveGames\241704685
Legilimens encountered an unexpected error
Traceback (most recent call last):
  File "legilimens.py", line 280, in main
  File "legilimens.py", line 259, in run
  File "legilimens.py", line 185, in _read_save
  File "legilimens.py", line 124, in __enter__
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\-user-\\AppData\\Local\\Hogwarts Legacy\\Saved\\SaveGames\\241704685'
If the problem persists, you can create an issue on GitHub with your save file attached:
https://github.com/Malin001/Legilimens-Hogwarts-Legacy-Collectible-Finder/issues

Press enter to close this window...
```

EDIT: edited username out

**Comment by SoftwareKater** [comment]
Hi RandomGuy908,

### Use file path NOT folder path

you have to put in the path to the file (you just gave the path to the folder):

`.sav file path: C:\Users\-user-\AppData\Local\Hogwarts Legacy\Saved\SaveGames\241704685\HL-00-XY.sav`

### Decompress before execution

Then you will probably encounter this error message: 

`SQLite was unable to read parts of the database`

You need to first decompress the save game file using this tool: https://www.nexusmods.com/hogwartslegacy/mods/1983. Follow the usage guide until step 6, from then on do instead:

step 7: Decompress your save file, e.g: `.\hlsaves.exe -d HL-03-05.orig HL-03-05.sav` 
step 8: execute Legilimens

### Use a backup

I suggest you copy the SaveGame folder to a convenient location. Use that copy as a target for HL Save Tool and Legilimens. If things go south you keep your save game, also you can skip step 9 an 10 of the usage guide. 


Happy achievement farming :)
Johannes
